environment:
  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    # We test on 32-bit Python 2.7, and 64-bit Python 3.x.
    # This is because it takes too long to serially go through six to eight
    # iterations.

    - PYTHON: "C:\\Python35-x64"
      NOXSESSION: "unit-3.5"
    - PYTHON: "C:\\Python27"
      NOXSESSION: "unit-2.7-32"

matrix:
    fast_finish: true

install:
  # Fetch submodules
  - git submodule update --init --recursive
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install -U pip

  # Fix MSVC builds for 64-bit Python. See:
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  # Install the mingw compiler, but only if we're on Python 2.7
  - pip install --no-cache-dir --pre --index https://pypi.anaconda.org/carlkl/simple "mingwpy; python_version < '3.5'"

  # Install Nox
  - C:\\Python36-x64\Scripts\pip install nox

build: off

test_script:
  # Run the project tests
  - C:\\Python36-x64\Scripts\nox
